image: node:22-alpine
create-pages:
  pages:
    publish: dist
  before_script:
    - corepack enable
    - corepack prepare pnpm@latest-10 --activate
    - pnpm install --frozen-lockfile
  script:
    - pnpm run build
