when:
  - event: push

steps:
  - name: Deploy
    image: docker.io/library/node:20-alpine
    commands:
      - npm install -g pnpm
      - pnpm install --frozen-lockfile
      - pnpm run build
      - pnpx wrangler pages deploy dist
    secrets: [ cloudflare_api_token, cloudflare_account_id, content_api_url, content_api_key ]
